/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import bbdd.Conexion;
import modelo.Paciente;
import utilidades.Utilidades;

/**
 *
 * @author lajot
 */
public class NuevoPaciente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevoPaciente.class.getName());

    /**
     * Creates new form NuevoPaciente
     */
    private String dniPrevio;
    
    public static String dni;
    
    public NuevoPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        Utilidades.centrarVentana(this);
        this.dniPrevio = dni;

    // ── DNI se carga automáticamente y no es editable ────────────
        CampoDni.setText(dni);
        CampoDni.setEditable(false);
        CampoDni.setBackground(new java.awt.Color(220, 220, 220));

        // ── Fecha mínima razonable para nacimiento ───────────────────
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.set(1900, 0, 1);
        jCalendar1.setMinSelectableDate(cal.getTime());
        jCalendar1.setMaxSelectableDate(new java.util.Date());

        // ── Carga códigos postales en el combo ───────────────────────
        Conexion.cargasComboCp(ComboCp);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CampoPersonal = new javax.swing.JTextField();
        CampoAntecedentes = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CampoDni = new javax.swing.JTextField();
        CampoNombre = new javax.swing.JTextField();
        CampoApellidos = new javax.swing.JTextField();
        CampoEmail = new javax.swing.JTextField();
        CampoTelefono = new javax.swing.JTextField();
        ComboCp = new javax.swing.JComboBox<>();
        RadioHombre = new javax.swing.JRadioButton();
        RadioMujer = new javax.swing.JRadioButton();
        RadioOtros = new javax.swing.JRadioButton();
        RadioSi = new javax.swing.JRadioButton();
        RadioHabitual = new javax.swing.JRadioButton();
        RadioNo = new javax.swing.JRadioButton();
        RadioOcasional = new javax.swing.JRadioButton();
        RadioNulo = new javax.swing.JRadioButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        BotonRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_good.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("NUEVO PACIENTE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salud", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Personal (alergias, cirujias, enfermedades, etc)");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Antecedentes familiares destacables");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(CampoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoAntecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(CampoAntecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(CampoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DNI");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellidos");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de nacimiento");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Codigo Postal");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sexo");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Consumo de alcohol");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tabaquismo");

        ComboCp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", " " }));

        RadioHombre.setForeground(new java.awt.Color(255, 255, 255));
        RadioHombre.setText("HOMBRE");

        RadioMujer.setForeground(new java.awt.Color(255, 255, 255));
        RadioMujer.setText("MUJER");

        RadioOtros.setForeground(new java.awt.Color(255, 255, 255));
        RadioOtros.setText("OTROS");

        RadioSi.setForeground(new java.awt.Color(255, 255, 255));
        RadioSi.setText("SI");

        RadioHabitual.setForeground(new java.awt.Color(255, 255, 255));
        RadioHabitual.setText("HABITUAL");

        RadioNo.setForeground(new java.awt.Color(255, 255, 255));
        RadioNo.setText("NO");

        RadioOcasional.setForeground(new java.awt.Color(255, 255, 255));
        RadioOcasional.setText("OCASIONAL");

        RadioNulo.setForeground(new java.awt.Color(255, 255, 255));
        RadioNulo.setText("NULO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ComboCp, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioSi)
                                    .addComponent(RadioOcasional)
                                    .addComponent(RadioMujer))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioHombre)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RadioNo)
                                            .addComponent(RadioHabitual))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(RadioNulo)
                                            .addComponent(RadioOtros)))))
                            .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CampoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioHombre)
                    .addComponent(RadioMujer)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(RadioSi)
                    .addComponent(RadioNo)
                    .addComponent(RadioOtros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioHabitual)
                    .addComponent(RadioNulo)
                    .addComponent(RadioOcasional)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        BotonRegistrar.setBackground(new java.awt.Color(0, 102, 102));
        BotonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegistrar.setText("REGISTRAR");
        BotonRegistrar.addActionListener(this::BotonRegistrarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
     registrarPaciente();      
    }//GEN-LAST:event_BotonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NuevoPaciente dialog = new NuevoPaciente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JTextField CampoAntecedentes;
    private javax.swing.JTextField CampoApellidos;
    private javax.swing.JTextField CampoDni;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoPersonal;
    private javax.swing.JTextField CampoTelefono;
    private javax.swing.JComboBox<String> ComboCp;
    private javax.swing.JRadioButton RadioHabitual;
    private javax.swing.JRadioButton RadioHombre;
    private javax.swing.JRadioButton RadioMujer;
    private javax.swing.JRadioButton RadioNo;
    private javax.swing.JRadioButton RadioNulo;
    private javax.swing.JRadioButton RadioOcasional;
    private javax.swing.JRadioButton RadioOtros;
    private javax.swing.JRadioButton RadioSi;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    private void registrarPaciente() {

        // ── Recoge datos del formulario ──────────────────────────────
        String nombre   = CampoNombre.getText().trim();
        String apell    = CampoApellidos.getText().trim();
        String telStr   = CampoTelefono.getText().trim();
        String email    = CampoEmail.getText().trim();
        String antFam   = CampoAntecedentes.getText().trim();
        String antPers  = CampoPersonal.getText().trim();
        java.util.Date fechaNac = jCalendar1.getDate();

        System.out.println("=== REGISTRAR PACIENTE ===");
        System.out.println("DNI:      " + dniPrevio);
        System.out.println("Nombre:   " + nombre);
        System.out.println("Apellidos:" + apell);
        System.out.println("Telefono: " + telStr);
        System.out.println("Email:    " + email);
        System.out.println("FechaNac: " + fechaNac);
        System.out.println("CP:       " + ComboCp.getSelectedItem());

        // ── Validaciones ─────────────────────────────────────────────
        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El nombre es obligatorio.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            CampoNombre.requestFocus();
            return;
        }
        if (apell.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Los apellidos son obligatorios.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            CampoApellidos.requestFocus();
            return;
        }
        if (fechaNac == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "La fecha de nacimiento es obligatoria.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (telStr.isEmpty() || !telStr.matches("\\d{9}")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El teléfono debe tener exactamente 9 dígitos.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            CampoTelefono.requestFocus();
            return;
        }
        if (!Utilidades.validarEmail(email)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El email no tiene un formato válido.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            CampoEmail.requestFocus();
            return;
        }
        if (ComboCp.getSelectedIndex() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Selecciona un código postal.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            ComboCp.requestFocus();
            return;
        }
        if (!RadioMujer.isSelected() && !RadioHombre.isSelected()
                && !RadioOtros.isSelected()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Selecciona el sexo.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!RadioNo.isSelected() && !RadioSi.isSelected()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Selecciona si el paciente fuma o no.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!RadioOcasional.isSelected() && !RadioHabitual.isSelected()
                && !RadioNulo.isSelected()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Selecciona el consumo de alcohol.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (antFam.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Los antecedentes familiares son obligatorios.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            CampoAntecedentes.requestFocus();
            return;
        }
        if (antPers.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Los antecedentes personales son obligatorios.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            CampoPersonal.requestFocus();
            return;
        }

        // ── Recoge valores de radio buttons ──────────────────────────
        String sexo    = RadioMujer.isSelected()     ? "M" :
                         RadioHombre.isSelected()    ? "H" : "OTROS";

        String tabaco  = RadioSi.isSelected()        ? "SI" : "NO";

        String alcohol = RadioOcasional.isSelected() ? "Ocasional" :
                         RadioHabitual.isSelected()  ? "Habitual"  : "Nulo";

        int cp  = Integer.parseInt(ComboCp.getSelectedItem().toString());
        int tel = Integer.parseInt(telStr);

        System.out.println("Sexo:    " + sexo);
        System.out.println("Tabaco:  " + tabaco);
        System.out.println("Alcohol: " + alcohol);
        System.out.println("CP:      " + cp);

        // ── Crea objeto Paciente ─────────────────────────────────────
        Paciente p = new Paciente(
            dniPrevio,
            nombre,
            apell,
            fechaNac,
            tel,
            email,
            cp,
            sexo,
            tabaco,
            alcohol,
            antFam,
            antPers,
            new java.util.Date()  
        );

        System.out.println("Llamando a Conexion.registrarPaciente...");
        boolean resultado = Conexion.registrarPaciente(p);
        System.out.println("Resultado: " + resultado);


        if (resultado) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Paciente registrado correctamente.",
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error en el registro del paciente. Inténtelo más tarde o "
                + "póngase en contacto con el administrador del sistema.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
}
