/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import bbdd.Conexion;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import utilidades.Utilidades;

/**
 *
 * @author lajot
 */
public class Pacientes extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pacientes.class.getName());

    /**
     * Creates new form Pacientes
     */
    public Pacientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        Utilidades.centrarVentana(this);
        Conexion.cargasComboCp(ComboCp);
        cargarTablaPacientes();
        desactivarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        CampoDni = new javax.swing.JTextField();
        CampoTelefono = new javax.swing.JTextField();
        CampoApellidos = new javax.swing.JTextField();
        ComboCp = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        BotonActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_good.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("PACIENTES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL PACIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DNI");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NOMBRE");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("APELLIDOS");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("TELEFONO");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CP");

        ComboCp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19))
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CampoNombre)
                    .addComponent(CampoApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(CampoTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(CampoDni, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(ComboCp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(CampoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CampoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboCp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "NOMBRE", "APELLIDOS", "TELEFONO", "CP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("LISTADO DE PACIENTES");

        BotonActualizar.setText("ACTUALIZAR");
        BotonActualizar.addActionListener(this::BotonActualizarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BotonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(BotonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
      actualizar();  // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Pacientes dialog = new Pacientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JTextField CampoApellidos;
    private javax.swing.JTextField CampoDni;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoTelefono;
    private javax.swing.JComboBox<String> ComboCp;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaPacientes() {
        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{"DNI", "NOMBRE", "APELLIDOS", "TELÉFONO", "CP"}, 0) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        Conexion.cargaTablaPacientes(modelo);
        Tabla.setModel(modelo);

        // ── Listener de selección de fila ────────────────────────────
        Tabla.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && Tabla.getSelectedRow() >= 0) {
                int fila = Tabla.getSelectedRow();

                String dni      = Tabla.getValueAt(fila, 0).toString();
                String nombre   = Tabla.getValueAt(fila, 1).toString();
                String apell    = Tabla.getValueAt(fila, 2).toString();
                String telefono = Tabla.getValueAt(fila, 3).toString();
                String cp       = Tabla.getValueAt(fila, 4).toString();

                System.out.println("Fila seleccionada → DNI: " + dni);

                // ── Rellena los campos con los datos de la fila ──────
                CampoDni.setText(dni);
                CampoNombre.setText(nombre);
                CampoApellidos.setText(apell);
                CampoTelefono.setText(telefono);

                // ── Selecciona el CP correcto en el combo ────────────
                int cpInt = Integer.parseInt(cp);
                for (int i = 0; i < ComboCp.getItemCount(); i++) {
                    if (String.valueOf(ComboCp.getItemAt(i))
                            .equals(String.valueOf(cpInt))) {
                        ComboCp.setSelectedIndex(i);
                        break;
                    }
                }

                activarFormulario();
            }
        });
    }

    private void activarFormulario() {
        CampoNombre.setEnabled(true);
        CampoApellidos.setEnabled(true);
        CampoTelefono.setEnabled(true);
        ComboCp.setEnabled(true);
        BotonActualizar.setEnabled(true);
    }

    private void desactivarFormulario() {
        CampoDni.setEnabled(false);
        CampoNombre.setEnabled(false);
        CampoApellidos.setEnabled(false);
        CampoTelefono.setEnabled(false);
        ComboCp.setEnabled(false);
        BotonActualizar.setEnabled(false);
        CampoDni.setText("");
        CampoNombre.setText("");
        CampoApellidos.setText("");
        CampoTelefono.setText("");
    }


    private void actualizar() {

        String dni      = CampoDni.getText().trim();
        String nombre   = CampoNombre.getText().trim();
        String apell    = CampoApellidos.getText().trim();
        String telefono = CampoTelefono.getText().trim();
        String cp       = ComboCp.getSelectedItem().toString();

        // ── Prints de depuración ─────────────────────────────────────
        System.out.println("=== ACTUALIZAR PACIENTE ===");
        System.out.println("DNI:      " + dni);
        System.out.println("Nombre:   " + nombre);
        System.out.println("Apellidos:" + apell);
        System.out.println("Teléfono: " + telefono);
        System.out.println("CP:       " + cp);

        // ── Validaciones ─────────────────────────────────────────────
        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El nombre es obligatorio.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            CampoNombre.requestFocus();
            return;
        }
        if (apell.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Los apellidos son obligatorios.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            CampoApellidos.requestFocus();
            return;
        }
        if (telefono.isEmpty() || !telefono.matches("\\d{9}")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El teléfono debe tener exactamente 9 dígitos.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            CampoTelefono.requestFocus();
            return;
        }
        if (cp.equals("Seleccione")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Selecciona un código postal.",
                "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ── Mete los datos en ArrayList y llama a Conexion ───────────
        // orden: [0]=dni, [1]=nombre, [2]=apellidos, [3]=telefono, [4]=cp
        ArrayList<String> datos = new ArrayList<>();
        datos.add(dni);
        datos.add(nombre);
        datos.add(apell);
        datos.add(telefono);
        datos.add(cp);

        System.out.println("Llamando a Conexion.actualizarPaciente...");
        boolean resultado = Conexion.actualizarPaciente(datos);
        System.out.println("Resultado: " + resultado);

        if (resultado) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Datos del paciente actualizados correctamente.",
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // ── Recarga la tabla con los datos actualizados ──────────
            DefaultTableModel modelo = new DefaultTableModel(
                new String[]{"DNI", "NOMBRE", "APELLIDOS", "TELÉFONO", "CP"}, 0) {
                public boolean isCellEditable(int r, int c) { return false; }
            };
            Conexion.cargaTablaPacientes(modelo);
            Tabla.setModel(modelo);
            desactivarFormulario();

        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error en la actualización del paciente. Inténtelo más tarde o "
                + "póngase en contacto con el administrador del sistema.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
}